modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IAFEnvoy/BGMPlayer/issues"
license = "LGPL-3.0"

[[mods]]
modId = "bgm_player"
version = "${version}"
displayName = "BGM Player"
authors = "IAFEnvoy"
description = '''
A more format supported, adjustable and continuous bgm system.
'''
logoFile = "logo.png"

[[dependencies.bgm_player]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bgm_player]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"
