modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/BGMPlayer/issues"
license = "LGPL-3.0"

[[mods]]
modId = "bgm_player"
version = "${version}"
displayName = "BGM Player"
authors = "IAFEnvoy"
description = '''
A more format supported, adjustable and continuous bgm system.
'''
logoFile = "logo.png"

[[dependencies.bgm_player]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bgm_player]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bgm_player.mixins.json"